# Generated by Django 6.0.1 on 2026-01-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocaCola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('volume_ml', models.CharField(choices=[('330', '330 ml'), ('500', '500 ml'), ('1000', '1 L'), ('1500', '1.5 L'), ('2000', '2 L')], default='500', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
